
plugin: aws_ec2
regions:
  - ca-central-1
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address
strict: False
  

