---
- hosts: all
  become: true
  vars:
    postgres_user: sonarqube
    postgres_password: sonarqube
    postgres_db: sonarqube

  tasks:
    - name: Update package lists
      apt: 
        update_cache: yes

    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Download SonarQube
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.1.69595.zip
        dest: /opt/sonarqube.zip

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Extract SonarQube archive
      unarchive:
        src: /opt/sonarqube.zip
        dest: /opt/
        remote_src: yes
      register: sonarqube_unarchived

    - name: Rename SonarQube directory
      command: mv /opt/sonarqube-9.9.1.69595 /opt/sonarqube
      when: sonarqube_unarchived is changed

    - name: Create SonarQube user
      user:
        name: sonarqube
        system: yes
        shell: /bin/bash

    - name: Change ownership of SonarQube directory
      file:
        path: /opt/sonarqube
        state: directory
        owner: sonarqube
        group: sonarqube
        recurse: yes

    - name: Copy SonarQube service file
      template:
        src: sonarqube.service.j2
        dest: /etc/systemd/system/sonarqube.service
        owner: root
        group: root
        mode: 0644

    - name: Unmask SonarQube service
      command: systemctl unmask sonarqube

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable SonarQube service
      command: systemctl start sonarqube
